#!/bin/sh
case "$1" in
  start)
    echo "LOADING FAULTY"
    modprobe faulty
    ;;
  stop)
    echo "UNLOADING FAULTY"
    rmmod faulty
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
esac
exit 0






